#!/bin/sh -eu

source $(dirname $0)/../../library/assert.subr

SCENARIO=project-everything

bolt clean

testing 'build'

bolt build

assert_exists \
    gen/bolt/compile/test.js \
    gen/bolt/compile/bootstrap.js \
    gen/bolt/inline/test.js \
    gen/bolt/module/test.ModuleOne.js \
    gen/bolt/module/test.ModuleTwo.js \
    gen/bolt/module/test.ModuleThree.js \
    gen/bolt/module/test.Main.js

bolt test
