
usage() {
    echo 'usage: bolt test CONFIG TEST ...'
    echo
    echo 'arguments:'
    echo '  CONFIG                   The bolt configuration file to be used for tests'
    echo '  TEST                     A test file. The test file may contain one or more'
    echo '                           test methods. `jssert` is exposed to the test file'
    echo '                           automatically.'
    echo
    echo 'example:'
    echo '  Run all tests.'
    echo
    echo '    bolt test bolt/config/test.js src/test/js/atomic/**/*.js'
    echo
    echo 'note:'
    echo '  Examples assume use of a shell with "**" glob support. This means either zsh or'
    echo '  bash 4.x with `shopt -s globstar` set. If you are an insolent mac user with a'
    echo '  default bash 3.x, this tool strongly recommends you upgrade (although defenestration'
    echo '  of said mac is also a valid option).'
    echo
    echo
    echo '  If you become desperate something like $(find src/test/js/atomic -name \*.js) could be'
    echo '  used as a substitute.'
    echo
}

if [ "$help_mode" = true ]; then
    usage
    exit 0
fi

if [ $# -lt 2 ]; then
    fail_usage 1 "Not enough arguments, must specify configuration and at least one test file."
fi

config="$1"; shift

if [ ! -f "$config" ]; then
    fail 10 "Could not find config file [$config]"
fi

for file in "$@"; do
    if [ ! -f "$file" ]; then
        fail 20 "Could not find test file [$file]"
    fi
done

exec node $base/bolt-test.js "$config" "$@"
